//Assignment Code and Character Set Arrays
var generateBtn = document.querySelector("#generate");
var passwordEmpty = [];
var charSetLowerLetters =  ["a", "b", "c", "d", "e", "f", "g", "h", "i","j","k","l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var charSetUpperLetters=[ "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",];
var charSetSpecialChar = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "-", "=", "/", "`", "~"];
var charNumbers = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"];

function generatePassword() {
//This code prevents the user from entering a number of characters that would cause the generated password to go outside of the diplayed box.
  while (true) {
    var characters = prompt("How many characters would you like in your password? Minimum of 8 characters are required.");
    if (characters >= 8 && characters <= 128) {
      break
    }
    alert("You've entered an invalid answer. Please try again")
  }
//Assignment variables for the prompts which allow the user to set criteria for their desired password.
  var specialChar = confirm("Would you like to include special characters like !, #, %, *, etc?");
  var numbers = confirm("Would you like to include numbers in your password?");
  var confirmedUpper = confirm("Would you like to include uppercase letters?");
  var confirmedLower = confirm("Would you like to include lowercase letters?");
//This stack of code puts the prompts into action. All arrays assigned at the beginning of the document are concatenated based on the choices made by the user.
  if (confirmedUpper && confirmedLower && numbers && specialChar) {
    charChoices = charSetLowerLetters.concat(charSetUpperLetters, charSetSpecialChar, charNumbers);
  }
  else if (confirmedUpper && confirmedLower && numbers) {
    charChoices = charSetLowerLetters.concat(charSetUpperLetters, charNumbers)
  }
  else if (confirmedUpper && confirmedLower && specialChar) {
    charChoices = charSetLowerLetters.concat(charSetUpperLetters, charSetSpecialChar)
  }
  else if (confirmedUpper && numbers && speicalChar) {
    charChoices = charSetUpperLetters.concat(charSetSpecialChar, charNumbers)
  }
  else if (confirmedLower && numbers && specialChar) {
    charChoices = charSetLowerLetters.concat(charNumbers, charSetSpecialChar)
  }
  else if (confirmedUpper && numbers) {
    charChoices = charSetUpperLetters.concat(numbers)
  }
  else if (confirmedUpper && specialChar) {
    charChoices = charSetUpperLetters.concat(charSetSpecialChar)
  }
  else if (confirmedLower && numbers) {
    charChoices = charSetLowerLetters.concat(charNumbers)
  }
  else if (confirmedUpper && confirmedLower) {
    charChoices = charSetLowerLetters.concat(charSetUpperLetters)
  }
  else if (specialChar && numbers) {
    charChoices = charSetSpecialChar.concat(charNumbers)
  }
  else if (confirmedUpper) {
    charChoices = charSetUpperLetters
  }
  else if (confirmedLower) {
    charChoices = charSetLowerLetters
  }
  else if (numbers) {
    charChoices = charNumbers
  }
  else if (specialChar) {
    charChoices = charSetSpecialChar
  }
  else {
    alert("Please pick at least one choice!")
    return "Refresh the page to try again!"
  }




//For loop that drives the code. Brackets represent a charAt() function iterates through the concatenated code generated by the charChoices variable and generate a password with a length dictated by the user at charChoices.length. This code is then pushed into the passwordEmpty array.f
  for (var i = 0; i < characters; i++) {
    var passwordGen = charChoices[Math.floor( Math.random() * charChoices.length)];
    passwordEmpty.push(passwordGen)
    }
 
  console.log("password: ", passwordEmpty)
  console.log("characters: ", characters)
  console.log("special characters: ", specialChar)
  console.log("numbers chosen: ", numbers)
  console.log("confirmedUpper response: ", confirmedUpper)
  console.log("confirmedLower response: ", confirmedLower)
//This code makes the passwordEmpty array a string so it can be displayed by the writePassword function and returns the final product as the result of the function.
  var passwordJoin = passwordEmpty.join("")
  return passwordJoin
}

//Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

//Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
